import { genAiModel } from "@/lib/utils";
import { NextResponse } from "next/server";

export async function GET() {
    const result = await genAiModel.generateContent([
        `Generate a list of top-performing theater shows. Each show should include the following details:

id: A unique identifier for the show (integer).
name: The name of the show (string).
revenue: The total revenue generated by the show in USD (integer).
percentOfTotal: The percentage of the total revenue that this show contributes (integer between 0 and 100).
image: A URL to an public image of the show (string and make extra sure that the url is real and working and don't use wikimedia urls use tmdb).
Provide at least 5 examples of shows with varying details.`
    ]);
    
    const jsonMatch = result.response.text().match(/\[[\s\S]*\]/);
    const jsonString = jsonMatch ? jsonMatch[0] : null;
    const jsonObject = JSON.parse(jsonString as string);
    
    return NextResponse.json(jsonObject)
}